### ISSUE TITLE
Support Laravel 5.2

### ISSUE THREAD

**Issue by EspadaV8** [sbarre/eloquent-versioned#20]
Laravel 5.2 changed the way global scopes are handled. The `VersioningScope` class needs updating so that it correctly adds/removed the scopes.

**Comment by sbarre** [comment]
I merged some old pending requests, and I'm going to look at the new 5.2 scopes to address this.

**Comment by sbarre** [comment]
I believe I've resolved this, I updated the trait to handle the new scoping, and it passes all tests with updated Laravel 5.2 dev requirements.
