### ISSUE TITLE
Maintain the versioned entities as a doubly linked list

### ISSUE THREAD

**Issue by EspadaV8** [sbarre/eloquent-versioned#3]
Would it be possible to have 2 extra columns in the table for 'previous_model_id' and 'next_model_id' along with methods to walk the list?

**Comment by sbarre** [comment]
Following up on the pull request, I think these utility methods are useful, but I I think I would try to implement them using the existing fields, as opposed to adding next/prev columns to the model.

Can you think of a reason simply querying a model's versions and using a given version numbers and incrementing/decrementing it would not work?

**Comment by EspadaV8** [comment]
Nope, not at the moment. Closing this to focus the comments on the pull request #7
