### ISSUE TITLE
Provide a way to diff between to entity versions

### ISSUE THREAD

**Issue by EspadaV8** [sbarre/eloquent-versioned#4]
This could possibly be another package, but it would be very useful if there was a way to return all fields that have been changed between 2 different versions of an entity, probably as a service, but also being able to call it on an existing model could be useful e.g.

``` php
$post = Post::last();
$changes = $post->changesSinceVersion(1);
dd($changes);
```

would give something like

``` php
array [
    'title' => 'Title for the first version of the post',
    'body' => 'Some text with a smelling mistake that was corrected in a later version',
]
```

**Comment by sbarre** [comment]
This is a good idea, I'm planning on spending some time this week adding new features and testing against L5.1 so I'll include this in my work.  Thanks!

**Comment by sbarre** [comment]
This should be resolved with the PR
